# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BwDn1aisWi3du9QXWghmziiHclWvITje
"""

import pandas as pd
from google.colab import drive

# Mount Google Drive
drive.mount('/content/drive')

# Define the path to your CSV file in Google Drive
file_path = '/content/drive/MyDrive/chatgpt_reviews.csv'

# Load the CSV file into a pandas DataFrame
try:
    df = pd.read_csv(file_path)
    print("DataFrame loaded successfully. First 5 rows:")
    print(df.head())
except FileNotFoundError:
    print(f"Error: The file '{file_path}' was not found. Please ensure the file exists in your Google Drive.")
except Exception as e:
    print(f"An error occurred while loading the file: {e}")

df.info()

df.describe()

"""standardizing column"""

# Standardize column names: convert to lowercase and replace spaces with underscores
df.columns = df.columns.str.lower().str.replace(' ', '_')

# Display the new column names to verify
print("New column names:")
print(df.columns)

print(df.isnull().sum())

# Convert 'review_date' column to datetime objects
df['review_date'] = pd.to_datetime(df['review_date'])

# Display the DataFrame information to verify the data type change
print(df.info())

"""Sentiment Analysis"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from collections import Counter
import re

# Import NLTK and initialize the SentimentIntensityAnalyzer if not already done in the previous step
import nltk
from nltk.sentiment.vader import SentimentIntensityAnalyzer

# Download the VADER lexicon (if not already downloaded)
try:
    nltk.data.find('sentiment/vader_lexicon.zip')
except LookupError:
    nltk.download('vader_lexicon')

sia = SentimentIntensityAnalyzer()

# Fill any NaN values in the 'review' column with an empty string to avoid errors during sentiment analysis
df['review'] = df['review'].fillna('')

# Apply sentiment analysis to the 'review' column
df['sentiment'] = df['review'].apply(sia.polarity_scores)

# Extract compound score and other scores into separate columns
df['compound_score'] = df['sentiment'].apply(lambda x: x['compound'])
df['pos'] = df['sentiment'].apply(lambda x: x['pos'])
df['neg'] = df['sentiment'].apply(lambda x: x['neg'])
df['neu'] = df['sentiment'].apply(lambda x: x['neu'])

# Classify sentiment based on compound score
def classify_sentiment(score):
    if score >= 0.05:
        return 'Positive'
    elif score <= -0.05:
        return 'Negative'
    else:
        return 'Neutral'

df['sentiment_label'] = df['compound_score'].apply(classify_sentiment)

# Display the first few rows with the new sentiment columns
print("DataFrame with sentiment scores and labels:")
display(df[['review', 'ratings', 'compound_score', 'pos', 'neg', 'neu', 'sentiment_label']].head())

"""### Sentiment Distribution Analysis

Let's visualize the distribution of positive, neutral, and negative sentiments among the reviews.
"""

# Calculate the count of each sentiment label
sentiment_counts = df['sentiment_label'].value_counts()

# Display the counts
print("Sentiment Distribution:")
print(sentiment_counts)

# Plot the sentiment distribution
plt.figure(figsize=(8, 6))
sns.barplot(x=sentiment_counts.index, y=sentiment_counts.values, palette='viridis')
plt.title('Distribution of Review Sentiments')
plt.xlabel('Sentiment')
plt.ylabel('Number of Reviews')
plt.show()

"""### Sentiment Distribution by Ratings

Let's visualize how sentiment varies across different rating categories.
"""

# Plot sentiment distribution bifurcated by ratings
plt.figure(figsize=(12, 7))
sns.countplot(data=df, x='ratings', hue='sentiment_label', palette='viridis', order=sorted(df['ratings'].unique()))
plt.title('Sentiment Distribution Across Different Ratings')
plt.xlabel('Ratings')
plt.ylabel('Number of Reviews')
plt.legend(title='Sentiment')
plt.show()

"""### Analyzing Positive Features

Let's delve into the content of positive reviews to understand what aspects are frequently praised by users.
"""

from nltk.corpus import stopwords
from collections import Counter
import re

# Download stopwords if not already downloaded
try:
    nltk.data.find('corpora/stopwords')
except LookupError:
    nltk.download('stopwords')

stop_words = set(stopwords.words('english'))

# Filter for positive reviews
positive_reviews_df = df[df['sentiment_label'] == 'Positive']

# Combine all positive review texts into a single string
all_positive_text = ' '.join(positive_reviews_df['review'].tolist())

# Preprocess the text:
# 1. Convert to lowercase
# 2. Remove punctuation and numbers
# 3. Tokenize words
# 4. Remove stop words

cleaned_text = re.sub(r'[^a-zA-Z\s]', '', all_positive_text.lower())
words = cleaned_text.split()
filtered_words = [word for word in words if word not in stop_words and len(word) > 2]

# Count word frequencies
word_counts = Counter(filtered_words)

# Get the 10 most common words
top_positive_words = word_counts.most_common(10)

print("Top 10 most common words in positive reviews:")
for word, count in top_positive_words:
    print(f"{word}: {count}")

import matplotlib.pyplot as plt
import seaborn as sns

# Prepare data for plotting
words, counts = zip(*top_positive_words)

plt.figure(figsize=(12, 8))
sns.barplot(x=list(counts), y=list(words), palette='viridis')
plt.title('Top 10 Most Common Words in Positive Reviews')
plt.xlabel('Frequency')
plt.ylabel('Words')
plt.show()

"""### Analyzing Negative Features

Let's investigate the content of negative reviews to understand common complaints or issues users face.
"""

from nltk.corpus import stopwords
from collections import Counter
import re

# Filter for negative reviews
negative_reviews_df = df[df['sentiment_label'] == 'Negative']

# Combine all negative review texts into a single string
all_negative_text = ' '.join(negative_reviews_df['review'].tolist())

# Preprocess the text:
# 1. Convert to lowercase
# 2. Remove punctuation and numbers
# 3. Tokenize words
# 4. Remove stop words

cleaned_text_neg = re.sub(r'[^a-zA-Z\s]', '', all_negative_text.lower())
words_neg = cleaned_text_neg.split()
filtered_words_neg = [word for word in words_neg if word not in stop_words and len(word) > 2]

# Count word frequencies
word_counts_neg = Counter(filtered_words_neg)

# Get the 10 most common words
top_negative_words = word_counts_neg.most_common(10)

print("Top 10 most common words in negative reviews:")
for word, count in top_negative_words:
    print(f"{word}: {count}")

import matplotlib.pyplot as plt
import seaborn as sns

# Prepare data for plotting
words_neg, counts_neg = zip(*top_negative_words)

plt.figure(figsize=(12, 8))
sns.barplot(x=list(counts_neg), y=list(words_neg), palette='magma')
plt.title('Top 10 Most Common Words in Negative Reviews')
plt.xlabel('Frequency')
plt.ylabel('Words')
plt.show()

"""### Review Evolution Over Time

Let's examine how sentiment and ratings have evolved over the review period.
"""

# Aggregate data by month to see trends
monthly_sentiment = df.groupby(df['review_date'].dt.to_period('M')).agg(
    avg_compound_score=('compound_score', 'mean'),
    positive_count=('sentiment_label', lambda x: (x == 'Positive').sum()),
    neutral_count=('sentiment_label', lambda x: (x == 'Neutral').sum()),
    negative_count=('sentiment_label', lambda x: (x == 'Negative').sum()),
    total_reviews=('sentiment_label', 'count')
).reset_index()

# Convert the 'review_date' (which is now Period objects) to datetime for plotting
monthly_sentiment['review_date'] = monthly_sentiment['review_date'].dt.to_timestamp()

# Calculate proportions
monthly_sentiment['positive_proportion'] = monthly_sentiment['positive_count'] / monthly_sentiment['total_reviews']
monthly_sentiment['neutral_proportion'] = monthly_sentiment['neutral_count'] / monthly_sentiment['total_reviews']
monthly_sentiment['negative_proportion'] = monthly_sentiment['negative_count'] / monthly_sentiment['total_reviews']

display(monthly_sentiment.head())

plt.figure(figsize=(15, 7))
sns.lineplot(data=monthly_sentiment, x='review_date', y='avg_compound_score', marker='o')
plt.title('Average Compound Sentiment Score Over Time (Monthly)')
plt.xlabel('Date')
plt.ylabel('Average Compound Score')
plt.grid(True)
plt.tight_layout()
plt.show()

plt.figure(figsize=(15, 7))
sns.lineplot(data=monthly_sentiment, x='review_date', y='positive_proportion', label='Positive', marker='o')
sns.lineplot(data=monthly_sentiment, x='review_date', y='neutral_proportion', label='Neutral', marker='o')
sns.lineplot(data=monthly_sentiment, x='review_date', y='negative_proportion', label='Negative', marker='o')
plt.title('Proportion of Sentiment Labels Over Time (Monthly)')
plt.xlabel('Date')
plt.ylabel('Proportion')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()